WebbAppGrp3/WebbApp/Areas/Admin/Controllers/ExpiredController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebbApp.DAL.Repositories;
using WebbApp.DAL.Interfaces;
using WebbApp.DAL.DB.Models;

namespace WebbApp.Areas.Admin.Controllers
{
    public class ExpiredController : Controller
    {
        IRepository<Item> itemRepo;

        public ExpiredController()
        {
            itemRepo = new ItemRepository();
        }

        // GET: Admin/Expired
        public ActionResult Index()
        {
            List<Item> list = itemRepo.GetAll().ToList();
            DateTime expDate = DateTime.Now;
            List<Item> deleteItems = list.FindAll(x => x.ExpirationDate < expDate);

            if (deleteItems == null || deleteItems.Count == 0)
            {
                return Content("No item to remove");
            }
            else
            {
                foreach (var item in deleteItems)
                {
                    foreach (var image in item.Images)
                    {
                        var filePath = Server.MapPath(image.Path);
                        if (System.IO.File.Exists(filePath))
                        {
                            System.IO.File.Delete(filePath);
                        }
                    }
                    itemRepo.Delete(item);
                }
                return Content("OK!");
            }
        }
    }
}

WebbAppGrp3/WebbApp/Areas/User/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebbApp.Areas.User.Controllers
{
    public class UserAccountController : Controller
    {
        // GET: User/UserAccount
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebbAppGrp3/WebbApp/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebbApp.ViewModels;
using WebbApp.DAL.Repositories;
using WebbApp.DAL.Interfaces;
using WebbApp.DAL.DB.Models;
using System.Security.Claims;
using Microsoft.AspNet.Identity;

namespace WebbApp.Controllers
{
    public class ItemController : Controller
    {
        private IRepository<Item> itemRepo;
        private IRepository<Category> categoryRepo;
        private IRepository<Region> regionRepo;
        private IRepository<City> cityRepo;
        private IRepository<Condition> conditionRepo;
        private IRepository<ApplicationUser> userRepo;

        public ItemController()
        {
            this.itemRepo = new ItemRepository();
            this.categoryRepo = new CategoryRepository();
            this.regionRepo = new RegionRepository();
            this.cityRepo = new CityRepository();
            this.conditionRepo = new ConditionRepository();
            this.userRepo = new UserRepository();
        }

        [AllowAnonymous]
        public ActionResult Index()
        {

            return PartialView();
        }

        [Authorize]
        [HttpGet]
        public ActionResult NewItem()
        {
            var ivm = new ItemViewModel();
            ivm.Categories = categoryRepo.GetAll().ToList();
            ivm.Conditions = conditionRepo.GetAll().ToList();
            ivm.Regions = regionRepo.GetAll().ToList();
            ivm.Cities = cityRepo.GetAll().ToList();
            return View(ivm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewItem(ItemViewModel model, IEnumerable<HttpPostedFileBase> files)
        {
            DateTime date = DateTime.Today;
            Guid newItemId = Guid.NewGuid();
            var newItem = new Item() { ItemID = newItemId, Title = model.Title, CreateDate = date, ExpirationDate = date.AddDays(7), Description = model.Description };
            newItem.CategoryId = model.Category.CategoryId;
            newItem.ConditionId = model.Condition.ConditionId;
            //newItem.CityId = model.City.CityId;
            //newItem.RegionId = model.Region.RegionId;
            newItem.ApplicationUserId = Guid.Parse(User.Identity.GetUserId());
            newItem.RegionId = model.Region.RegionId;
            newItem.CityId = model.City.CityId;
            itemRepo.Add(newItem);

            if (files != null && files.ElementAt(0) != null && files.ElementAt(0).ContentLength != 0)
            {
                foreach (var file in files)
                {
                    string newImg = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Images"), newImg);
                    if (newImg.ToLower().EndsWith(".jpg") || newImg.ToLower().EndsWith(".png"))
                    {
                        file.SaveAs(path);

                        using (MemoryStream ms = new MemoryStream())
                        {
                            file.InputStream.CopyTo(ms);
                            byte[] array = ms.GetBuffer();
                        }
                        Image newImage = new Image();
                        newImage.ImageId = Guid.NewGuid();
                        newImage.Path = "../Images/" + newImg;
                        //newImage.Path = newImg;
                        newImage.ItemID = newItemId;
                        newImage.Item = newItem;
                        itemRepo.AddImage(newImage);
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        public ActionResult DisplaySingleItem(Guid itemID)
        {
            var repoItem = itemRepo.GetById(itemID);
            var newViewModel = new ItemViewModel(repoItem.ItemID,
                repoItem.Title,
                repoItem.Description,
                repoItem.CreateDate,
                repoItem.ExpirationDate,
                repoItem.City,
                repoItem.Condition,
                repoItem.Region,
                repoItem.Category,
                repoItem.Images);
            newViewModel.UploaderID = repoItem.ApplicationUserId.ToString();
            return View(newViewModel);
        }

        [AllowAnonymous]
        public ActionResult ListAllItems()
        {
            var ItemsFromRepo = itemRepo.GetAll();
            var ViewModelItems = new List<ItemViewModel>();

            foreach (var repoItem in ItemsFromRepo)
            {
                var newViewModel = new ItemViewModel(repoItem.ItemID, repoItem.Title, repoItem.Description, repoItem.CreateDate, repoItem.ExpirationDate, repoItem.City, repoItem.Condition, repoItem.Region, repoItem.Category, repoItem.Images);
                ViewModelItems.Add(newViewModel);
            }

            return View(ViewModelItems);
        }

        [Authorize]
        [HttpPost]
        public ActionResult RemoveItem(Guid itemID)
        {
            var itemToDelete = itemRepo.GetById(itemID);

            foreach (var image in itemToDelete.Images)
            {
                var filePath = Server.MapPath(image.Path);
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
            }

            itemRepo.Delete(itemID);
            if (Request.IsAjaxRequest())
            {
                return Content("/Item/ListAllItems");
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpGet]
        public ActionResult EditItem(Guid ItemID)
        {
            var item = itemRepo.GetById(ItemID);
            var ivm = new ItemViewModel() { ItemID = item.ItemID, Title = item.Title, Description = item.Description, };
            ivm.Categories = categoryRepo.GetAll().ToList();
            ivm.SelectedCategoryId = item.CategoryId;
            ivm.Conditions = conditionRepo.GetAll().ToList();
            ivm.SelectedConditionId = item.ConditionId;
            ivm.Regions = regionRepo.GetAll().ToList();
            ivm.SelectedRegionId = item.RegionId;
            ivm.Cities = cityRepo.GetAll().ToList();
            ivm.SelectedCityId = item.CityId;
            ivm.CreateDate = DateTime.Now;
            ivm.ExpirationDate = DateTime.Now.AddDays(7);
            return View(ivm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditItem(ItemViewModel viewItem, IEnumerable<HttpPostedFileBase> files)
        {
            Item edit = null;
            ModelState.Remove("Image");
            //if (ModelState.IsValid)
            //{
            edit = new Item()
            {
                ItemID = viewItem.ItemID,
                Title = viewItem.Title,
                Description = viewItem.Description,
                CreateDate = viewItem.CreateDate,
                ExpirationDate = viewItem.ExpirationDate,
                CategoryId = viewItem.Category.CategoryId,
                ConditionId = viewItem.Condition.ConditionId,
                CityId = viewItem.City.CityId,
                RegionId = viewItem.Region.RegionId

            };
            itemRepo.Update(edit);
            //}
            if (files != null && files.ElementAt(0) != null && files.ElementAt(0).ContentLength != 0)
            {
                foreach (var file in files)
                {
                    string newImg = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Images"), newImg);
                    if (newImg.ToLower().EndsWith(".jpg") || newImg.ToLower().EndsWith(".png"))
                    {
                        file.SaveAs(path);

                        using (MemoryStream ms = new MemoryStream())
                        {
                            file.InputStream.CopyTo(ms);
                            byte[] array = ms.GetBuffer();
                        }
                        Image newImage = new Image();
                        newImage.ImageId = Guid.NewGuid();
                        newImage.Path = "../Images/" + newImg;
                        newImage.ItemID = edit.ItemID;
                        newImage.Item = edit;
                        itemRepo.AddImage(newImage);
                    }
                }
            }
            return RedirectToAction("ListAllItems");
        }

        public ActionResult GetUploaderEmail(Guid UserID)
        {
            var user = userRepo.GetById(UserID);
            var email = string.Empty;

            if(user != null)
            {
                email = user.Email;
            }

            if(email != string.Empty)
            {
                return Content(email);
            }
            else
            {
                return Content("Couldn't find email.");
            }
        }

    }
}

WebbAppGrp3/WebbApp/Areas/User/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Give It Away Now!", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)

                    </li>
                    <li>
                        @*//TODO KEVIN - fr SPA to MVC
                            @Html.ActionLink("Items", "ListAllItems", "Item", new { area = "" }, null)*@
                        @Ajax.ActionLink("Items", "ListAllItems", "Item", null,
                        new AjaxOptions
                        {
                            UpdateTargetId = "PartialContainer",
                            InsertionMode = InsertionMode.Replace,
                            HttpMethod = "GET"
                        })
                    </li>

                    @if (User.IsInRole("Admin") || User.IsInRole("User"))
                    {
                        <li>
                            @Html.ActionLink("New Item", "NewItem", "Item", new { area = "" }, null)
                        </li>
                    }

                    @if (HttpContext.Current.User.IsInRole("Admin"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("User", "Index", "User", new { area = "Admin" }, null)</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Category", "Index", "Category", new { area = "Admin" }, null)</li>
                                <li>@Html.ActionLink("City", "Index", "City", new { area = "Admin" }, null)</li>
                                <li>@Html.ActionLink("Condition", "Index", "Condition", new { area = "Admin" }, null)</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Remove expired posts", "Index", "Expired", new { area = "Admin" }, new { id = "removeexpired" })</li>
                            </ul>
                        </li>
                    }
                    @if (HttpContext.Current.User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("My Account", "Index", "UserAccount", new { area = "User" }, null)</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content ">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/alertify")
    @Scripts.Render("~/bundles/expired")
    @RenderSection("scripts", required: false)
</body>
</html>